### PR TITLE
EIP1-3549: EIP1-4173: add SourceType.anonymous-elector-document

### PR DESCRIPTION
**Pull request by sentioservices**
This PR adds SourceType.anonymous-elector-document to the print-api-sqs-messaging.yaml spec

### CODE REVIEW

**Comment by matt-wills-valtech** [comment]
Would you mind adding this to the swagger spec as well and then tracing it through from `AnoymousElectorDocumentController.generateAnonymousElectorDocument()`?

If not, then perhaps it's best to create a bug against EIP1-407?

@Neil-Massey  FYI

**Review by vishalgupta-valtech — APPROVED** [review]
lgtm

**Review by matt-wills-valtech — APPROVED** [review]

**Comment by vishalgupta-valtech** [comment]
> Would you mind adding this to the swagger spec as well and then tracing it through from `AnoymousElectorDocumentController.generateAnonymousElectorDocument()`?
> 
> If not, then perhaps it's best to create a bug against [EIP1-3823](https://technologyprogramme.atlassian.net/browse/EIP1-3823)?
> 
> @Neil-Massey FYI

Is this related to this PR? Could this change be done as a part of new PR if that requires liquibase changes?

**Comment by matt-wills-valtech** [comment]
> > Would you mind adding this to the swagger spec as well and then tracing it through from `AnoymousElectorDocumentController.generateAnonymousElectorDocument()`?
> > If not, then perhaps it's best to create a bug against [EIP1-3823](https://technologyprogramme.atlassian.net/browse/EIP1-3823)?
> > @Neil-Massey FYI
> 
> Is this related to this PR? Could this change be done as a part of new PR if that requires liquibase changes?

It's not related to the story, but it's related to the change to `SourceType`, which Rob has added to the SQS spec. It doesn't require liquibase changes.

We could create a bug or separate issue for it. The original story is done, so I thought it would be easiest just to squeeze it in here if Rob doesn't mind, but we can do it separately if he prefers 👍

**Comment by vishalgupta-valtech** [comment]
> > > Would you mind adding this to the swagger spec as well and then tracing it through from `AnoymousElectorDocumentController.generateAnonymousElectorDocument()`?
> > > If not, then perhaps it's best to create a bug against [EIP1-3823](https://technologyprogramme.atlassian.net/browse/EIP1-3823)?
> > > @Neil-Massey FYI
> > 
> > 
> > Is this related to this PR? Could this change be done as a part of new PR if that requires liquibase changes?
> 
> It's not related to the story, but it's related to the change to `SourceType`, which Rob has added to the SQS spec. It doesn't require liquibase changes.
> 
> We could create a bug or separate issue for it. The original story is done, so I thought it would be easiest just to squeeze it in here if Rob doesn't mind, but we can do it separately if he prefers 👍

@matt-wills-valtech @sentioservices has added `Liquibase` changes to this PR which isn't in the scope of this PR. Can I suggest a separate PR for this (not a blocker though)

**Pull request merged**
